### ISSUE TITLE
贵博客RSS链接貌似变成localhost了，能否更新一下

### ISSUE THREAD

**Issue by wonderffee** [slarkcoder/ss_status#1]
从博文过来的，问题与此repo无关，抱歉

其他的问题：
1. 找不到 services.slarker.me 的服务器 DNS 地址。
2. 能否提供一个archive链接，这样可以一键查看所有博文标题列表

**Comment by slarkcoder** [comment]
抱歉，现在才看到这个 issues..

services.slarker.me 已经换成了 https://ssrouter.org
因为我的博客是 Ghost，暂时没有提供 Archive 功能，可以通过 RSS 来订阅我的博客：https://slarker.me/rss/，谢谢！
